### ISSUE TITLE
fails to build with ghc-8.8

### ISSUE THREAD

**Issue by juhp** [psibi/fakedata#5]
Not completely sure if this is a more general issue but FYI:

In Stackage Nightly (ghc-8.8.1)

```
    Preprocessing library for fakedata-0.3.0..
    Building library for fakedata-0.3.0..
    [  6 of 294] Compiling Config
    
    /var/stackage/work/unpack-dir/unpacked/fakedata-0.3.0-29bee891d16361edbdf0eab1ca8835dc307511faa242308d7b1cdba103cf4eeb/src/Config.hs:387:7: error:
        • Could not deduce (MonadFail m) arising from a use of ‘parseMonad’
          from the context: (MonadThrow m, MonadIO m)
            bound by the type signature for:
                       fetchData :: forall (m :: * -> *) a.
                                    (MonadThrow m, MonadIO m) =>
                                    FakerSettings
                                    -> SourceData -> (FakerSettings -> Value -> Parser a) -> m a
            at src/Config.hs:(369,1)-(374,8)
          Possible fix:
            add (MonadFail m) to the context of
              the type signature for:
                fetchData :: forall (m :: * -> *) a.
                             (MonadThrow m, MonadIO m) =>
                             FakerSettings
                             -> SourceData -> (FakerSettings -> Value -> Parser a) -> m a
        • In a stmt of a 'do' block: parseMonad (parser settings) yaml
          In the expression:
            do afile <- getSourceFile fname
               bs <- liftIO $ BS.readFile afile
               yaml <- decodeThrow bs
               let nhash = HM.insert ckey yaml cache
               ....
          In a case alternative:
              Nothing
                -> do afile <- getSourceFile fname
                      bs <- liftIO $ BS.readFile afile
                      yaml <- decodeThrow bs
                      ....
        |
    387 |       parseMonad (parser settings) yaml
        |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    /var/stackage/work/unpack-dir/unpacked/fakedata-0.3.0-29bee891d16361edbdf0eab1ca8835dc307511faa242308d7b1cdba103cf4eeb/src/Config.hs:408:16: error:
        • Could not deduce (MonadFail m) arising from a use of ‘parseMonad’
          from the context: (MonadThrow m, MonadIO m)
            bound by the type signature for:
                       fetchDataSingle :: forall (m :: * -> *).
                                          (MonadThrow m, MonadIO m) =>
                                          FakerSettings
                                          -> SourceData
                                          -> (FakerSettings -> Value -> Parser Text)
                                          -> m (Vector Text)
            at src/Config.hs:(390,1)-(395,20)
          Possible fix:
            add (MonadFail m) to the context of
              the type signature for:
                fetchDataSingle :: forall (m :: * -> *).
                                   (MonadThrow m, MonadIO m) =>
                                   FakerSettings
                                   -> SourceData
                                   -> (FakerSettings -> Value -> Parser Text)
                                   -> m (Vector Text)
        • In the second argument of ‘(<$>)’, namely
            ‘parseMonad (parser settings) yaml’
          In a stmt of a 'do' block:
            pure <$> parseMonad (parser settings) yaml
          In the expression:
            do afile <- getSourceFile fname
               bs <- liftIO $ BS.readFile afile
               yaml <- decodeThrow bs
               let nhash = HM.insert ckey yaml cache
               ....
        |
    408 |       pure <$> parseMonad (parser settings) yaml
        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
